// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "app/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// EventRepositoryMock is an autogenerated mock type for the EventRepository type
type EventRepositoryMock struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: id
func (_m *EventRepositoryMock) GetByID(id int64) (*domain.Event, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*domain.Event, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *domain.Event); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUnprocessed provides a mock function with given fields: limit
func (_m *EventRepositoryMock) ListUnprocessed(limit int) ([]domain.Event, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for ListUnprocessed")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.Event, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.Event); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkProcessedBatch provides a mock function with given fields: ids
func (_m *EventRepositoryMock) MarkProcessedBatch(ids []int64) error {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessedBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]int64) error); ok {
		r0 = rf(ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: eventType, payload
func (_m *EventRepositoryMock) Save(eventType string, payload interface{}) error {
	ret := _m.Called(eventType, payload)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(eventType, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventRepositoryMock creates a new instance of EventRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventRepositoryMock {
	mock := &EventRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
