// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// JWTHelperMock is an autogenerated mock type for the JWTHelper type
type JWTHelperMock struct {
	mock.Mock
}

// GenerateAccessToken provides a mock function with given fields: userID, roles
func (_m *JWTHelperMock) GenerateAccessToken(userID string, roles []string) (string, error) {
	ret := _m.Called(userID, roles)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string) (string, error)); ok {
		return rf(userID, roles)
	}
	if rf, ok := ret.Get(0).(func(string, []string) string); ok {
		r0 = rf(userID, roles)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(userID, roles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJWTHelperMock creates a new instance of JWTHelperMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTHelperMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTHelperMock {
	mock := &JWTHelperMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
