// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	repositories "app/internal/repositories"

	mock "github.com/stretchr/testify/mock"
)

// StoreMock is an autogenerated mock type for the Store type
type StoreMock struct {
	mock.Mock
}

// Outbox provides a mock function with no fields
func (_m *StoreMock) Outbox() repositories.EventRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Outbox")
	}

	var r0 repositories.EventRepository
	if rf, ok := ret.Get(0).(func() repositories.EventRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.EventRepository)
		}
	}

	return r0
}

// Tokens provides a mock function with no fields
func (_m *StoreMock) Tokens() repositories.TokenRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tokens")
	}

	var r0 repositories.TokenRepository
	if rf, ok := ret.Get(0).(func() repositories.TokenRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.TokenRepository)
		}
	}

	return r0
}

// Users provides a mock function with no fields
func (_m *StoreMock) Users() repositories.UserRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Users")
	}

	var r0 repositories.UserRepository
	if rf, ok := ret.Get(0).(func() repositories.UserRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.UserRepository)
		}
	}

	return r0
}

// NewStoreMock creates a new instance of StoreMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreMock {
	mock := &StoreMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
