// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "app/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TokenRepositoryMock is an autogenerated mock type for the TokenRepository type
type TokenRepositoryMock struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *TokenRepositoryMock) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByUser provides a mock function with given fields: userID
func (_m *TokenRepositoryMock) DeleteByUser(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByHash provides a mock function with given fields: hash
func (_m *TokenRepositoryMock) GetByHash(hash string) (*domain.Token, error) {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Token, error)); ok {
		return rf(hash)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Token); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *TokenRepositoryMock) GetByID(id uint) (*domain.Token, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Token, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Token); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: userID
func (_m *TokenRepositoryMock) GetByUserID(userID string) ([]*domain.Token, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domain.Token, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domain.Token); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: token
func (_m *TokenRepositoryMock) Save(token *domain.Token) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Token) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTokenRepositoryMock creates a new instance of TokenRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenRepositoryMock {
	mock := &TokenRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
