// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	repositories "app/internal/repositories"

	mock "github.com/stretchr/testify/mock"

	stores "app/internal/stores"
)

// UnitOfWorkMock is an autogenerated mock type for the UnitOfWork type
type UnitOfWorkMock struct {
	mock.Mock
}

// DoRegistration provides a mock function with given fields: fn
func (_m *UnitOfWorkMock) DoRegistration(fn func(repositories.UserRepository, repositories.EventRepository) error) error {
	ret := _m.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for DoRegistration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(repositories.UserRepository, repositories.EventRepository) error) error); ok {
		r0 = rf(fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with no fields
func (_m *UnitOfWorkMock) Store() stores.Store {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 stores.Store
	if rf, ok := ret.Get(0).(func() stores.Store); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(stores.Store)
		}
	}

	return r0
}

// NewUnitOfWorkMock creates a new instance of UnitOfWorkMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnitOfWorkMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnitOfWorkMock {
	mock := &UnitOfWorkMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
